/**
 * Interface copy. `kk` is the source of truth; `ru` is typed against it so a
 * missing translation is a compile error.
 */

export const kk = {
  'app.name': 'Anyq',
  'app.tagline': 'Сұрағыңды анимацияға айналдыр',

  'common.signIn': 'Кіру',
  'common.signUp': 'Тіркелу',
  'common.logOut': 'Шығу',
  'common.save': 'Сақтау',
  'common.saved': 'Сақталды',
  'common.cancel': 'Бас тарту',
  'common.delete': 'Жою',
  'common.edit': 'Өңдеу',
  'common.close': 'Жабу',
  'common.retry': 'Қайталау',
  'common.search': 'Іздеу',
  'common.open': 'Ашу',
  'common.rename': 'Атын өзгерту',
  'common.export': 'Экспорт',
  'common.loading': 'Жүктелуде',
  'common.language': 'Тіл',
  'common.kazakh': 'Қазақша',
  'common.russian': 'Орысша',
  'common.auto': 'Авто',
  'common.subject': 'Пән',
  'common.grade': 'Сынып',
  'common.topic': 'Тақырып',
  'common.date': 'Күні',
  'common.status': 'Күйі',
  'common.actions': 'Әрекеттер',
  'common.all': 'Барлығы',
  'common.confirm': 'Растау',
  'common.required': 'міндетті',
  'common.menu': 'Мәзір',
  'theme.toLight': 'Ашық режимге ауысу',
  'theme.toDark': 'Қараңғы режимге ауысу',
  'theme.label': 'Көрініс',
  'common.of': '/',

  'subject.math': 'Математика',
  'subject.geometry': 'Геометрия',
  'subject.physics': 'Физика',
  'subject.chemistry': 'Химия',
  'subject.biology': 'Биология',
  'subject.informatics': 'Информатика',

  'role.student': 'Оқушы',
  'role.teacher': 'Мұғалім',
  'role.studentDesc': 'Сұрақ қой, түсіндірме мен анимация ал, кітапханаға сақта.',
  'role.teacherDesc':
    'Осының бәрі, қосымша СОР/СОЖ құрастыру, жұмыс тексеру және баланс.',

  'nav.explain': 'Түсіндіру',
  'nav.library': 'Кітапхана',
  'nav.generate': 'Құрастыру',
  'nav.check': 'Тексеру',
  'nav.billing': 'Баланс',
  'nav.settings': 'Баптаулар',

  // Landing -----------------------------------------------------------------
  'landing.nav.how': 'Қалай жұмыс істейді',
  'landing.nav.examples': 'Мысалдар',
  'landing.nav.about': 'Біз туралы',
  'landing.hero.title': 'Кез келген сұрақ — қысқа анимациялық түсіндірме',
  'landing.hero.subtitle':
    'Сұрағыңды қазақша немесе орысша жаз. Anyq оны қадамдап түсіндіріп, сол түсіндірмені геометриялық анимацияға айналдырады. Күндер емес — минуттар ішінде.',
  'landing.hero.cta': 'Тегін бастау',
  'landing.hero.secondary': 'Мысалдарды көру',
  'landing.hero.caption':
    'Пифагор теоремасы — Anyq құрастырған анимациядан алынған кадр.',
  'landing.compare.title': 'Оқығаннан гөрі көрген түсінікті',
  'landing.compare.subtitle':
    'Тұтқаны солға-оңға сүйреңіз. Сол жағында — оқулықтағы мәтін, оң жағында — сол мәтіннен жасалған анимация.',
  'landing.compare.hint': 'Тұтқаны сүйреңіз',
  'landing.compare.textLabel': 'Оқулық мәтіні',
  'landing.compare.videoLabel': 'Anyq анимациясы',
  'landing.compare.sliderLabel': 'Мәтін мен анимацияны салыстыру тұтқасы',
  'landing.compare.textTitle': 'Пифагор теоремасы',
  'landing.compare.textBody':
    'Тік бұрышты үшбұрыштың гипотенузасының квадраты катеттерінің квадраттарының қосындысына тең. Дәлелдеу үшін қабырғасы a + b болатын шаршы салып, оның ішіне катеттері a және b болатын төрт бірдей тік бұрышты үшбұрышты орналастырамыз. Үшбұрыштарды екі түрлі тәсілмен орналастырғанда, шаршының бос қалған ауданы бірінші жағдайда a² + b², екінші жағдайда c² болады. Екі жағдайда да алынып тасталған үшбұрыштардың жалпы ауданы бірдей болғандықтан, қалған аудандар да өзара тең: a² + b² = c². Бұдан гипотенузаның ұзындығы c = √(a² + b²) екені шығады. Теорема кез келген тік бұрышты үшбұрыш үшін орындалады және кері тұжырымы да дұрыс: егер үшбұрыштың қабырғалары a² + b² = c² қатынасын қанағаттандырса, онда бұл үшбұрыш тік бұрышты болады.',
  'landing.how.title': 'Үш қадам',
  'landing.how.step1.title': 'Сұра',
  'landing.how.step1.body':
    'Сұрағыңды өз сөзіңмен жаз. Тіл автоматты анықталады, қаласаң өзің таңдай аласың.',
  'landing.how.step2.title': 'Түсіндір',
  'landing.how.step2.body':
    'Anyq жауапты қадамдарға бөліп жазады: не берілген, қандай заңдылық қолданылады, нәтиже қандай.',
  'landing.how.step3.title': 'Анимациялау',
  'landing.how.step3.body':
    'Әр қадам геометриялық сахнаға айналады. Нәтижесі — бірнеше минутта дайын болатын қысқа түсіндірме бейне.',
  'landing.examples.title': 'Дайын мысалдар',
  'landing.examples.subtitle':
    'Бәрі Anyq арқылы құрастырылған. Меңзерді апарсаңыз — ойнайды.',
  'landing.examples.play': 'Ойнату үшін меңзерді апарыңыз',
  'landing.why.title': 'Неге қазақ тілінде?',
  'landing.why.body1':
    'Бір анимациялық түсіндірмені қолмен жасауға аниматордың бірнеше күні кетеді. Аудиториясы шағын тіл үшін мұндай контентті көлемді түрде шығару экономикалық тұрғыдан тиімсіз. Сондықтан қазақ тілінде сапалы визуалды оқу материалы жоқтың қасы.',
  'landing.why.body2':
    'Anyq осы жұмысты автоматтандырады. Үлкен тілдердегі оқушылар визуалды түсіндірме көріп жатқанда, қазақ тілді оқушы тек қалың мәтінмен қалмауы керек.',
  'landing.why.stat1': 'Бір анимацияны қолмен жасау уақыты',
  'landing.why.stat1v': '3–5 күн',
  'landing.why.stat2': 'Anyq арқылы',
  'landing.why.stat2v': '4 минут',
  'landing.why.stat3': 'Қазақша қолдау',
  'landing.why.stat3v': 'Әдепкі тіл',
  'landing.team.title': 'Кім жасады',
  'landing.team.subtitle': 'Екі адамнан құралған команда.',
  'landing.contact.title': 'Сұрақтарыңыз бар ма?',
  'landing.contact.body': 'Кез келген сұрақ бойынша хабарласыңыз — қуана жауап береміз.',
  'landing.contact.phone': 'Телефон',
  'landing.contact.email': 'Email',
  'landing.cta.title': 'Бірінші сұрағыңды қой',
  'landing.cta.body': 'Тіркелу тегін. Оқушыларға шектеусіз түсіндірме.',
  'landing.footer.product': 'Өнім',
  'landing.footer.company': 'Компания',
  'landing.footer.legal': 'Құқықтық',
  'landing.footer.privacy': 'Құпиялық саясаты',
  'landing.footer.terms': 'Пайдалану шарттары',
  'landing.footer.contact': 'Байланыс',
  'landing.footer.rights': 'Барлық құқықтар қорғалған.',

  // Auth ---------------------------------------------------------------------
  'auth.signup.title': 'Тіркелу',
  'auth.signup.subtitle': 'Бір минут кетеді. Карта қажет емес.',
  'auth.signup.roleLabel': 'Сіз кімсіз?',
  'auth.signup.roleError': 'Рөлді таңдаңыз',
  'auth.signup.submit': 'Аккаунт жасау',
  'auth.signup.haveAccount': 'Аккаунтыңыз бар ма?',
  'auth.signin.title': 'Қайта кіру',
  'auth.signin.subtitle': 'Жұмыс кеңістігіңізге оралыңыз.',
  'auth.signin.submit': 'Кіру',
  'auth.signin.noAccount': 'Аккаунтыңыз жоқ па?',
  'auth.signin.forgot': 'Құпиясөзді ұмыттыңыз ба?',
  'auth.signin.invalid': 'Email немесе құпиясөз қате. Қайта көріңіз.',
  'auth.field.name': 'Аты-жөні',
  'auth.field.email': 'Email',
  'auth.field.password': 'Құпиясөз',
  'auth.error.nameRequired': 'Атыңызды жазыңыз',
  'auth.error.emailRequired': 'Email жазыңыз',
  'auth.error.emailInvalid': 'Email форматы дұрыс емес',
  'auth.error.passwordRequired': 'Құпиясөз жазыңыз',
  'auth.error.passwordShort': 'Кемінде 8 таңба болсын',
  'auth.error.form': 'Форманы толық толтырыңыз.',
  'auth.error.emailTaken': 'Бұл email тіркелген. Кіріп көріңіз.',
  'auth.error.tooMany': 'Тым көп әрекет. Біраз күте тұрыңыз.',
  'auth.error.network': 'Сервер жауап бермеді. Байланысты тексеріңіз.',
  'auth.error.unknown': 'Бірдеңе дұрыс болмады. Қайта көріңіз.',
  'auth.password.hint': 'Кемінде 8 таңба.',

  // Explain ------------------------------------------------------------------
  'explain.title': 'Түсіндіру',
  'explain.history': 'Тарих',
  'explain.newChat': 'Жаңа сұрақ',
  'explain.historyEmpty': 'Әзірше сұрақ жоқ.',
  'explain.inputLabel': 'Сұрағыңыз',
  'explain.placeholder': 'Мысалы: Неге аспан көк болып көрінеді?',
  'explain.submit': 'Түсіндір',
  'explain.langLabel': 'Жауап тілі',
  'explain.emptyTitle': 'Сұрағыңнан баста',
  'explain.emptyBody':
    'Кез келген математика немесе жаратылыстану сұрағын жаз. Төмендегі мысалдардың бірін басып та көруге болады.',
  'explain.examplesTitle': 'Мысал сұрақтар',
  'explain.stage.understand': 'Сұрақты талдау',
  'explain.stage.write': 'Түсіндірме жазу',
  'explain.stage.render': 'Анимацияны рендерлеу',
  'explain.generatingTitle': 'Дайындалып жатыр',
  'explain.generatingBody':
    'Анимацияны рендерлеу бірнеше минут алуы мүмкін. Бетті жаппай тұра тұрыңыз.',
  'explain.resultTitle': 'Түсіндірме',
  'explain.saveToLibrary': 'Кітапханаға сақтау',
  'explain.savedToLibrary': 'Кітапханада сақтаулы',
  'explain.partialTitle': 'Анимация дайын болмады',
  'explain.partialBody':
    'Түсіндірме дайын, бірақ бұл жолы анимацияны құрастыра алмадық. Түсіндірмені оқи беруге болады немесе анимацияны қайта сұрауға болады.',
  'explain.partialRetry': 'Анимацияны қайта құрастыру',
  'explain.errorTitle': 'Бірдеңе болмай қалды',
  'explain.errorBody':
    'Бұл сұраққа жауап дайындай алмадық. Сұрақты сәл өзгертіп немесе қайта жіберіп көріңіз.',
  'explain.demoLabel': 'Демо күйі',
  'explain.demo.ok': 'Сәтті',
  'explain.demo.partial': 'Анимациясыз',
  'explain.demo.error': 'Қате',
  'explain.demoHint': 'Демо: келесі сұрақ қандай нәтиже беретінін таңдаңыз.',
  'explain.savedToast': 'Кітапханаға сақталды',
  'explain.costNote': 'Бір түсіндірме — {cost}',

  // Player -------------------------------------------------------------------
  'player.play': 'Ойнату',
  'player.pause': 'Тоқтату',
  'player.replay': 'Қайта ойнату',
  'player.seek': 'Уақыт бойынша жылжыту',
  'player.label': 'Анимация ойнатқышы',
  'player.failed': 'Видеоны ойнату мүмкін болмады.',
  'player.download': 'Видеоны жүктеп алу',
  'explain.fromLibrary': 'Кітапханадан',
  'explain.fromLibraryHint': 'Бұл сұраққа жауап дайын болған, сондықтан бірден келді.',
  'explain.matchedQuestion': 'Ұқсас сұраққа жауап: «{question}»',
  'explain.askAgain': 'Жаңадан сұрау',
  'explain.offline': 'Сервермен байланыс жоқ. Қайта қосылуда…',
  'explain.timedOut': 'Жауап тым ұзаққа созылды. Ол дайын болса, тарихтан табасыз.',
  'explain.noAnswerYet':
    'Бұл сұрақ жауапсыз қалған. Сұрақ қайта терілді — «Қайталау» басыңыз.',
  'explain.historyUnreadable': 'Бұл жазбаны ашу мүмкін болмады. Қайта көріңіз.',
  'explain.failed': 'Түсіндірме дайындалмады.',
  'narration.label': 'Дауыс',
  'narration.on': 'Дауыспен — шамамен бір минут',
  'narration.off': 'Дауыссыз — қысқа, тек жазулар',
  'narration.enable': 'Дауысты қосу',
  'narration.disable': 'Дауысты өшіру',
  'narration.voice.aigul': 'Айгүл',
  'narration.voice.daulet': 'Дәулет',
  'narration.voiceLabel': 'Дауысты таңдау',
  'effort.label': 'Сапасы',
  'effort.low': 'Жеңіл',
  'effort.low.hint': '480p, 15 к/с',
  'effort.low.wait': 'Ең жылдам',
  'effort.medium': 'Қалыпты',
  'effort.medium.hint': '720p, 30 к/с',
  'effort.medium.wait': 'Әдеттегі күту',
  'effort.high': 'Жоғары',
  'effort.high.hint': '1080p, 60 к/с',
  'effort.high.wait': 'Бірнеше минутқа дейін',
  'length.label': 'Ұзақтығы',
  'length.short': 'Қысқа',
  'length.short.hint': '~30-40 сек',
  'length.medium': 'Орташа',
  'length.medium.hint': '~50-60 сек',
  'length.long': 'Ұзақ',
  'length.long.hint': '~80-90 сек',
  'player.reducedMotion':
    'Жүйеңізде қозғалысты азайту қосулы. Анимация автоматты ойналмайды.',

  // Library ------------------------------------------------------------------
  'library.title': 'Кітапхана',
  'library.loadFailed': 'Кітапхананы жүктеу мүмкін болмады.',
  'library.saveFailed': 'Өзгерісті сақтау мүмкін болмады.',
  'library.subtitle': 'Сақталған түсіндірмелер.',
  'library.searchPlaceholder': 'Сұрақ бойынша іздеу',
  'library.sort.new': 'Алдымен жаңасы',
  'library.sort.old': 'Алдымен ескісі',
  'library.sort.az': 'Әліпби бойынша',
  'library.sortLabel': 'Сұрыптау',
  'library.count': '{n} түсіндірме',
  'library.emptyTitle': 'Кітапхана бос',
  'library.emptyBody': 'Сақтаған түсіндірмелеріңіз осында жиналады.',
  'library.emptyCta': 'Бірінші сұрағыңды қой',
  'library.noResultsTitle': 'Ештеңе табылмады',
  'library.noResultsBody': 'Іздеу сөзін немесе сүзгіні өзгертіп көріңіз.',
  'library.clearFilters': 'Сүзгілерді тазалау',
  'library.deleteTitle': 'Түсіндірмені жою',
  'library.deleteBody':
    '«{title}» кітапханадан жойылады. Бұл әрекетті қайтару мүмкін емес.',
  'library.deleted': 'Түсіндірме жойылды',
  'library.renameTitle': 'Атын өзгерту',
  'library.renameLabel': 'Жаңа атауы',
  'library.renamed': 'Атауы жаңартылды',
  'library.cardMenu': '{title} — әрекеттер',

  // Generate -----------------------------------------------------------------
  'generate.title': 'Бағалау жұмысын құрастыру',
  'generate.subtitle': 'СОР, СОЖ немесе қысқа тест.',
  'generate.form': 'Параметрлер',
  'generate.type': 'Жұмыс түрі',
  'generate.type.sor': 'СОР',
  'generate.type.soch': 'СОЖ',
  'generate.type.quiz': 'Тест',
  'generate.topicPlaceholder': 'Мысалы: Квадрат теңдеулер',
  'generate.count': 'Сұрақ саны',
  'generate.difficulty': 'Деңгейі',
  'generate.difficulty.easy': 'Жеңіл',
  'generate.difficulty.medium': 'Орташа',
  'generate.difficulty.hard': 'Күрделі',
  'generate.submit': 'Құрастыру',
  'generate.regenerate': 'Қайта құрастыру',
  'generate.preview': 'Алдын ала қарау',
  'generate.previewEmptyTitle': 'Құжат әлі жоқ',
  'generate.previewEmptyBody':
    'Сол жақтағы параметрлерді толтырып, «Құрастыру» түймесін басыңыз.',
  'generate.generating': 'Сұрақтар құрастырылуда',
  'generate.errorTitle': 'Құрастыру сәтсіз аяқталды',
  'generate.errorBody': 'Қайта көріңіз немесе параметрлерді өзгертіңіз.',
  'generate.topicRequired': 'Тақырыпты жазыңыз',
  'generate.regenerateQuestion': '{n}-сұрақты қайта құрастыру',
  'generate.editQuestion': '{n}-сұрақ мәтіні',
  'generate.marks': '{n} балл',
  'generate.totalMarks': 'Жалпы: {n} балл',
  'generate.instructions': 'Нұсқаулық',
  'generate.instructionsBody':
    'Барлық сұраққа жауап беріңіз. Шешімнің барысын толық жазыңыз. Уақыты — 40 минут.',
  'generate.docHeaderName': 'Аты-жөні',
  'generate.docHeaderClass': 'Сынып',
  'generate.docHeaderDate': 'Күні',
  'generate.exportDocx': 'DOCX',
  'generate.print': 'Басып шығару',
  'generate.docxSoon': 'DOCX әзірше дайын емес',
  'generate.exporting': 'Экспорт жүріп жатыр',
  'generate.saved': 'Жұмыс құрастырылды',
  'generate.questionUpdated': 'Сұрақ жаңартылды',
  'generate.tab.document': 'Құжат',
  'generate.tab.key': 'Бағалау критерийі',
  'generate.criteria.question': 'Сұрақ',
  'generate.criteria.level': 'Критерий',
  'generate.criteria.marks': 'Балл',
  'generate.criteria.full': 'Шешімнің толық барысы мен дұрыс жауап жазылған',
  'generate.criteria.partial': 'Жауап дұрыс, бірақ шешім барысы жазылмаған',
  'generate.criteria.start': 'Дұрыс әдіс таңдалған, шешім аяқталмаған',
  'generate.criteria.note':
    'Критерий әр сұраққа автоматты түрде құрастырылады. Мұғалім өзгерте алады.',

  // Check --------------------------------------------------------------------
  'check.title': 'Жұмыстарды тексеру',
  'check.subtitle': 'Оқушы жұмыстарын жүктеңіз — баллдары мен қателері шығады.',
  'check.dropTitle': 'Файлдарды осында тастаңыз',
  'check.dropBody': 'PDF, JPG немесе PNG. Бір файл — бір оқушы жұмысы.',
  'check.browse': 'Файл таңдау',
  'check.uploadDemo': 'Демо файлдарды қосу',
  'check.queue': 'Жүктелген файлдар',
  'check.process': 'Тексеруді бастау',
  'check.processing': 'Тексерілуде',
  'check.removeFile': '{name} файлын алып тастау',
  'check.status.queued': 'Кезекте',
  'check.status.uploading': 'Жүктелуде',
  'check.status.processing': 'Тексерілуде',
  'check.status.done': 'Дайын',
  'check.status.failed': 'Сәтсіз',
  'check.results': 'Нәтижелер',
  'check.col.student': 'Оқушы',
  'check.col.score': 'Балл',
  'check.col.file': 'Файл',
  'check.emptyTitle': 'Әзірге жүктелген жұмыс жоқ',
  'check.emptyBody':
    'Жоғарыдағы аймаққа файлдарды тастаңыз немесе демо файлдарды қосыңыз.',
  'check.noResultsTitle': 'Нәтиже жоқ',
  'check.noResultsBody': 'Файлдарды жүктеп, тексеруді бастаңыз.',
  'check.detail': 'Жұмыс егжей-тегжейі',
  'check.detailFor': '{student} — жұмыс нәтижесі',
  'check.breakdown': 'Сұрақтар бойынша',
  'check.question': '{n}-сұрақ',
  'check.override': 'Баллды түзету',
  'check.overrideLabel': 'Жаңа балл',
  'check.overrideSave': 'Баллды сақтау',
  'check.overridden': 'Мұғалім түзеткен',
  'check.overrideSaved': 'Балл жаңартылды',
  'check.exportResults': 'Нәтижелерді экспорттау',
  'check.fileFailed': 'Файлды тани алмадық. Сурет анық емес болуы мүмкін.',
  'check.processed': '{n} жұмыс тексерілді',

  // Billing ------------------------------------------------------------------
  'billing.title': 'Баланс',
  'billing.subtitle': 'Не үшін қанша алынғаны — толық ашық.',
  'billing.balance': 'Ағымдағы баланс',
  'billing.topUp': 'Толықтыру',
  'billing.topUpTitle': 'Балансты толықтыру',
  'billing.topUpAmount': 'Сома',
  'billing.topUpDone': 'Баланс толықтырылды',
  'billing.zeroTitle': 'Баланс нөл',
  'billing.zeroBody': 'Жаңа әрекеттер үшін балансты толықтыру керек.',
  'billing.lowTitle': 'Баланс аз қалды',
  'billing.lowBody': 'Ағымдағы қарқынмен шамамен бір аптаға жетеді.',
  'billing.usage': 'Осы айдағы шығыс',
  'billing.period': 'Кезең',
  'billing.period.month': 'Осы ай',
  'billing.period.quarter': 'Соңғы 3 ай',
  'billing.period.year': 'Осы жыл',
  'billing.prices': 'Әрекет құны',
  'billing.price.explanation': 'Бір түсіндірме + анимация',
  'billing.price.assessment': 'Бір СОР/СОЖ немесе тест',
  'billing.price.grading': 'Бір тексерілген жұмыс',
  'billing.history': 'Транзакциялар',
  'billing.col.action': 'Әрекет',
  'billing.col.qty': 'Саны',
  'billing.col.amount': 'Сома',
  'billing.action.explanation': 'Түсіндірме',
  'billing.action.assessment': 'Бағалау жұмысы',
  'billing.action.grading': 'Жұмыс тексеру',
  'billing.action.topup': 'Толықтыру',
  'billing.historyEmptyTitle': 'Транзакция жоқ',
  'billing.historyEmptyBody': 'Бірінші әрекеттен кейін осында тізім пайда болады.',
  'billing.exportHistory': 'Тарихты экспорттау',
  'billing.txTitle': 'Транзакция',
  'billing.demoState': 'Демо баланс күйі',
  'billing.state.healthy': 'Жеткілікті',
  'billing.state.low': 'Аз',
  'billing.state.zero': 'Нөл',
  'billing.chartLabel': '{period} бойынша күнделікті шығыс, теңгемен',
  'billing.spentTotal': 'Барлығы жұмсалды',
  'billing.explanations': 'Түсіндірме',
  'billing.assessments': 'Бағалау жұмысы',
  'billing.gradings': 'Тексерілген жұмыс',

  // Settings -----------------------------------------------------------------
  'settings.title': 'Баптаулар',
  'settings.profile': 'Профиль',
  'settings.profileDesc': 'Аты-жөні, email және аватар.',
  'settings.avatar': 'Аватар',
  'settings.avatarHint': 'Аты-жөніңіздің бірінші әріптерінен жасалады.',
  'settings.language': 'Тіл',
  'settings.languageDesc': 'Интерфейс тілі және түсіндірменің әдепкі тілі.',
  'settings.uiLang': 'Интерфейс тілі',
  'settings.explainLang': 'Түсіндірменің әдепкі тілі',
  'settings.theme': 'Көрініс',
  'settings.themeDesc': 'Ашық немесе қараңғы.',
  'settings.theme.light': 'Ашық',
  'settings.theme.dark': 'Қараңғы',
  'settings.theme.system': 'Жүйе бойынша',
  'settings.plan': 'Тариф',
  'settings.planDesc': 'Ағымдағы тариф және есеп айырысу.',
  'settings.plan.student': 'Оқушы — тегін',
  'settings.plan.teacher': 'Мұғалім — қолданғаныңа қарай',
  'settings.plan.studentBody': 'Шектеусіз түсіндірме және кітапхана.',
  'settings.plan.teacherBody': 'Барлық мүмкіндік. Әр әрекет балансынан алынады.',
  'settings.danger': 'Қауіпті аймақ',
  'settings.dangerDesc': 'Аккаунтты жою — қайтарылмайтын әрекет.',
  'settings.deleteAccount': 'Аккаунтты жою',
  'settings.deleteTitle': 'Аккаунтты жоясыз ба?',
  'settings.deleteBody':
    'Барлық түсіндірме, кітапхана және тарих жойылады. Растау үшін төменге {word} деп жазыңыз.',
  'settings.deleteConfirmLabel': 'Растау сөзі',
  'settings.deleteWord': 'ЖОЮ',
  'settings.deleteMismatch': 'Растау сөзі сәйкес келмейді',
  'settings.savedToast': 'Өзгерістер сақталды',
  'settings.saveError': 'Сақтау мүмкін болмады. Қайта көріңіз.',
  'settings.saving': 'Сақталуда',
} as const

export type StringKey = keyof typeof kk

export const ru: Record<StringKey, string> = {
  'app.name': 'Anyq',
  'app.tagline': 'Преврати свой вопрос в анимацию',

  'common.signIn': 'Войти',
  'common.signUp': 'Регистрация',
  'common.logOut': 'Выйти',
  'common.save': 'Сохранить',
  'common.saved': 'Сохранено',
  'common.cancel': 'Отмена',
  'common.delete': 'Удалить',
  'common.edit': 'Изменить',
  'common.close': 'Закрыть',
  'common.retry': 'Повторить',
  'common.search': 'Поиск',
  'common.open': 'Открыть',
  'common.rename': 'Переименовать',
  'common.export': 'Экспорт',
  'common.loading': 'Загрузка',
  'common.language': 'Язык',
  'common.kazakh': 'Казахский',
  'common.russian': 'Русский',
  'common.auto': 'Авто',
  'common.subject': 'Предмет',
  'common.grade': 'Класс',
  'common.topic': 'Тема',
  'common.date': 'Дата',
  'common.status': 'Статус',
  'common.actions': 'Действия',
  'common.all': 'Все',
  'common.confirm': 'Подтвердить',
  'common.required': 'обязательно',
  'common.menu': 'Меню',
  'theme.toLight': 'Переключить на светлую тему',
  'theme.toDark': 'Переключить на тёмную тему',
  'theme.label': 'Тема',
  'common.of': '/',

  'subject.math': 'Математика',
  'subject.geometry': 'Геометрия',
  'subject.physics': 'Физика',
  'subject.chemistry': 'Химия',
  'subject.biology': 'Биология',
  'subject.informatics': 'Информатика',

  'role.student': 'Ученик',
  'role.teacher': 'Учитель',
  'role.studentDesc':
    'Задавайте вопросы, получайте объяснение и анимацию, сохраняйте в библиотеку.',
  'role.teacherDesc': 'Всё то же плюс генерация СОР/СОЧ, проверка работ и баланс.',

  'nav.explain': 'Объяснить',
  'nav.library': 'Библиотека',
  'nav.generate': 'Генерация',
  'nav.check': 'Проверка',
  'nav.billing': 'Баланс',
  'nav.settings': 'Настройки',

  'landing.nav.how': 'Как это работает',
  'landing.nav.examples': 'Примеры',
  'landing.nav.about': 'О нас',
  'landing.hero.title': 'Любой вопрос — короткое анимированное объяснение',
  'landing.hero.subtitle':
    'Напишите вопрос на казахском или русском. Anyq разберёт его по шагам и превратит объяснение в геометрическую анимацию. За минуты, а не за дни.',
  'landing.hero.cta': 'Начать бесплатно',
  'landing.hero.secondary': 'Посмотреть примеры',
  'landing.hero.caption': 'Теорема Пифагора — кадр из анимации, созданной Anyq.',
  'landing.compare.title': 'Увидеть понятнее, чем прочитать',
  'landing.compare.subtitle':
    'Перетащите ручку влево или вправо. Слева — текст из учебника, справа — анимация, сделанная из этого текста.',
  'landing.compare.hint': 'Потяните ручку',
  'landing.compare.textLabel': 'Текст учебника',
  'landing.compare.videoLabel': 'Анимация Anyq',
  'landing.compare.sliderLabel': 'Ручка сравнения текста и анимации',
  'landing.compare.textTitle': 'Теорема Пифагора',
  'landing.compare.textBody':
    'Квадрат гипотенузы прямоугольного треугольника равен сумме квадратов катетов. Для доказательства построим квадрат со стороной a + b и разместим внутри него четыре одинаковых прямоугольных треугольника с катетами a и b. При двух разных способах размещения свободная площадь квадрата в первом случае равна a² + b², а во втором — c². Поскольку суммарная площадь убранных треугольников в обоих случаях одинакова, равны и оставшиеся площади: a² + b² = c². Отсюда длина гипотенузы равна c = √(a² + b²). Теорема выполняется для любого прямоугольного треугольника, и обратное утверждение тоже верно: если стороны треугольника удовлетворяют соотношению a² + b² = c², то этот треугольник прямоугольный.',
  'landing.how.title': 'Три шага',
  'landing.how.step1.title': 'Спросить',
  'landing.how.step1.body':
    'Напишите вопрос своими словами. Язык определяется автоматически, но его можно выбрать вручную.',
  'landing.how.step2.title': 'Объяснить',
  'landing.how.step2.body':
    'Anyq разбирает ответ по шагам: что дано, какая закономерность применяется, какой получается результат.',
  'landing.how.step3.title': 'Анимировать',
  'landing.how.step3.body':
    'Каждый шаг становится геометрической сценой. На выходе — короткое объясняющее видео за считаные минуты.',
  'landing.examples.title': 'Готовые примеры',
  'landing.examples.subtitle':
    'Всё сделано в Anyq. Наведите курсор — начнётся воспроизведение.',
  'landing.examples.play': 'Наведите курсор для воспроизведения',
  'landing.why.title': 'Почему на казахском?',
  'landing.why.body1':
    'На одно анимированное объяснение вручную у аниматора уходит несколько дней. Для языка с небольшой аудиторией выпускать такой контент в объёме экономически невыгодно. Поэтому качественных визуальных учебных материалов на казахском почти нет.',
  'landing.why.body2':
    'Anyq автоматизирует эту работу. Пока ученики в больших языках смотрят визуальные объяснения, казахоязычный ученик не должен оставаться один на один с плотным текстом.',
  'landing.why.stat1': 'Одна анимация вручную',
  'landing.why.stat1v': '3–5 дней',
  'landing.why.stat2': 'Через Anyq',
  'landing.why.stat2v': '4 минуты',
  'landing.why.stat3': 'Казахский язык',
  'landing.why.stat3v': 'Язык по умолчанию',
  'landing.team.title': 'Кто это сделал',
  'landing.team.subtitle': 'Команда из двух человек.',
  'landing.contact.title': 'Есть вопросы?',
  'landing.contact.body': 'Свяжитесь с нами по любому вопросу — с радостью ответим.',
  'landing.contact.phone': 'Телефон',
  'landing.contact.email': 'Email',
  'landing.cta.title': 'Задайте первый вопрос',
  'landing.cta.body': 'Регистрация бесплатна. Для учеников — без ограничений.',
  'landing.footer.product': 'Продукт',
  'landing.footer.company': 'Компания',
  'landing.footer.legal': 'Правовое',
  'landing.footer.privacy': 'Политика конфиденциальности',
  'landing.footer.terms': 'Условия использования',
  'landing.footer.contact': 'Контакты',
  'landing.footer.rights': 'Все права защищены.',

  'auth.signup.title': 'Регистрация',
  'auth.signup.subtitle': 'Займёт минуту. Карта не нужна.',
  'auth.signup.roleLabel': 'Кто вы?',
  'auth.signup.roleError': 'Выберите роль',
  'auth.signup.submit': 'Создать аккаунт',
  'auth.signup.haveAccount': 'Уже есть аккаунт?',
  'auth.signin.title': 'С возвращением',
  'auth.signin.subtitle': 'Вернитесь в своё рабочее пространство.',
  'auth.signin.submit': 'Войти',
  'auth.signin.noAccount': 'Нет аккаунта?',
  'auth.signin.forgot': 'Забыли пароль?',
  'auth.signin.invalid': 'Неверный email или пароль. Попробуйте ещё раз.',
  'auth.field.name': 'Имя и фамилия',
  'auth.field.email': 'Email',
  'auth.field.password': 'Пароль',
  'auth.error.nameRequired': 'Укажите имя',
  'auth.error.emailRequired': 'Укажите email',
  'auth.error.emailInvalid': 'Неверный формат email',
  'auth.error.passwordRequired': 'Укажите пароль',
  'auth.error.passwordShort': 'Минимум 8 символов',
  'auth.error.form': 'Заполните форму полностью.',
  'auth.error.emailTaken': 'Этот email уже зарегистрирован. Попробуйте войти.',
  'auth.error.tooMany': 'Слишком много попыток. Подождите немного.',
  'auth.error.network': 'Сервер не ответил. Проверьте соединение.',
  'auth.error.unknown': 'Что-то пошло не так. Попробуйте ещё раз.',
  'auth.password.hint': 'Минимум 8 символов.',

  'explain.title': 'Объяснить',
  'explain.history': 'История',
  'explain.newChat': 'Новый вопрос',
  'explain.historyEmpty': 'Вопросов пока нет.',
  'explain.inputLabel': 'Ваш вопрос',
  'explain.placeholder': 'Например: Почему небо кажется синим?',
  'explain.submit': 'Объяснить',
  'explain.langLabel': 'Язык ответа',
  'explain.emptyTitle': 'Начните с вопроса',
  'explain.emptyBody':
    'Напишите любой вопрос по математике или естественным наукам. Можно нажать на один из примеров ниже.',
  'explain.examplesTitle': 'Примеры вопросов',
  'explain.stage.understand': 'Разбор вопроса',
  'explain.stage.write': 'Написание объяснения',
  'explain.stage.render': 'Рендер анимации',
  'explain.generatingTitle': 'Готовим ответ',
  'explain.generatingBody':
    'Рендер анимации может занять несколько минут. Не закрывайте страницу.',
  'explain.resultTitle': 'Объяснение',
  'explain.saveToLibrary': 'Сохранить в библиотеку',
  'explain.savedToLibrary': 'Сохранено в библиотеке',
  'explain.partialTitle': 'Анимация не получилась',
  'explain.partialBody':
    'Объяснение готово, но анимацию в этот раз собрать не удалось. Текст можно читать, а анимацию — запросить снова.',
  'explain.partialRetry': 'Собрать анимацию заново',
  'explain.errorTitle': 'Что-то пошло не так',
  'explain.errorBody':
    'Не удалось подготовить ответ на этот вопрос. Переформулируйте вопрос или отправьте ещё раз.',
  'explain.demoLabel': 'Демо-состояние',
  'explain.demo.ok': 'Успех',
  'explain.demo.partial': 'Без анимации',
  'explain.demo.error': 'Ошибка',
  'explain.demoHint': 'Демо: выберите, каким будет результат следующего вопроса.',
  'explain.savedToast': 'Сохранено в библиотеку',
  'explain.costNote': 'Одно объяснение — {cost}',

  'player.play': 'Воспроизвести',
  'player.pause': 'Пауза',
  'player.replay': 'Сначала',
  'player.seek': 'Перемотка',
  'player.label': 'Проигрыватель анимации',
  'player.failed': 'Не удалось воспроизвести видео.',
  'player.download': 'Скачать видео',
  'explain.fromLibrary': 'Из библиотеки',
  'explain.fromLibraryHint': 'На этот вопрос уже был готов ответ, поэтому он пришёл сразу.',
  'explain.matchedQuestion': 'Ответ на похожий вопрос: «{question}»',
  'explain.askAgain': 'Спросить заново',
  'explain.offline': 'Нет связи с сервером. Переподключаемся…',
  'explain.timedOut': 'Ответ идёт слишком долго. Если он готов, он появится в истории.',
  'explain.noAnswerYet':
    'На этот вопрос ответа так и не пришло. Вопрос подставлен обратно — нажмите «Повторить».',
  'explain.historyUnreadable': 'Не удалось открыть эту запись. Попробуйте ещё раз.',
  'explain.failed': 'Объяснение не получилось.',
  'narration.label': 'Голос',
  'narration.on': 'С голосом — примерно минута',
  'narration.off': 'Без голоса — короче, только подписи',
  'narration.enable': 'Включить озвучку',
  'narration.disable': 'Отключить озвучку',
  'narration.voice.aigul': 'Айгүл',
  'narration.voice.daulet': 'Дәулет',
  'narration.voiceLabel': 'Выбор голоса',
  'effort.label': 'Качество',
  'effort.low': 'Лёгкое',
  'effort.low.hint': '480p, 15 к/с',
  'effort.low.wait': 'Быстрее всего',
  'effort.medium': 'Обычное',
  'effort.medium.hint': '720p, 30 к/с',
  'effort.medium.wait': 'Обычное ожидание',
  'effort.high': 'Высокое',
  'effort.high.hint': '1080p, 60 к/с',
  'effort.high.wait': 'До нескольких минут',
  'length.label': 'Длительность',
  'length.short': 'Короткое',
  'length.short.hint': '~30-40 сек',
  'length.medium': 'Среднее',
  'length.medium.hint': '~50-60 сек',
  'length.long': 'Длинное',
  'length.long.hint': '~80-90 сек',
  'player.reducedMotion':
    'В системе включено уменьшение движения. Анимация не запускается автоматически.',

  'library.title': 'Библиотека',
  'library.loadFailed': 'Не удалось загрузить библиотеку.',
  'library.saveFailed': 'Не удалось сохранить изменение.',
  'library.subtitle': 'Сохранённые объяснения.',
  'library.searchPlaceholder': 'Поиск по вопросу',
  'library.sort.new': 'Сначала новые',
  'library.sort.old': 'Сначала старые',
  'library.sort.az': 'По алфавиту',
  'library.sortLabel': 'Сортировка',
  'library.count': 'Объяснений: {n}',
  'library.emptyTitle': 'Библиотека пуста',
  'library.emptyBody': 'Сохранённые объяснения будут собираться здесь.',
  'library.emptyCta': 'Задать первый вопрос',
  'library.noResultsTitle': 'Ничего не найдено',
  'library.noResultsBody': 'Измените запрос или фильтры.',
  'library.clearFilters': 'Сбросить фильтры',
  'library.deleteTitle': 'Удалить объяснение',
  'library.deleteBody': '«{title}» будет удалено из библиотеки. Действие необратимо.',
  'library.deleted': 'Объяснение удалено',
  'library.renameTitle': 'Переименовать',
  'library.renameLabel': 'Новое название',
  'library.renamed': 'Название обновлено',
  'library.cardMenu': '{title} — действия',

  'generate.title': 'Генерация работы',
  'generate.subtitle': 'СОР, СОЧ или короткий тест.',
  'generate.form': 'Параметры',
  'generate.type': 'Тип работы',
  'generate.type.sor': 'СОР',
  'generate.type.soch': 'СОЧ',
  'generate.type.quiz': 'Тест',
  'generate.topicPlaceholder': 'Например: Квадратные уравнения',
  'generate.count': 'Количество вопросов',
  'generate.difficulty': 'Сложность',
  'generate.difficulty.easy': 'Лёгкая',
  'generate.difficulty.medium': 'Средняя',
  'generate.difficulty.hard': 'Высокая',
  'generate.submit': 'Сгенерировать',
  'generate.regenerate': 'Сгенерировать заново',
  'generate.preview': 'Предпросмотр',
  'generate.previewEmptyTitle': 'Документа ещё нет',
  'generate.previewEmptyBody': 'Заполните параметры слева и нажмите «Сгенерировать».',
  'generate.generating': 'Генерируем вопросы',
  'generate.errorTitle': 'Не удалось сгенерировать',
  'generate.errorBody': 'Попробуйте ещё раз или измените параметры.',
  'generate.topicRequired': 'Укажите тему',
  'generate.regenerateQuestion': 'Пересобрать вопрос {n}',
  'generate.editQuestion': 'Текст вопроса {n}',
  'generate.marks': '{n} б.',
  'generate.totalMarks': 'Всего: {n} баллов',
  'generate.instructions': 'Инструкция',
  'generate.instructionsBody':
    'Ответьте на все вопросы. Записывайте ход решения полностью. Время — 40 минут.',
  'generate.docHeaderName': 'Имя и фамилия',
  'generate.docHeaderClass': 'Класс',
  'generate.docHeaderDate': 'Дата',
  'generate.exportDocx': 'DOCX',
  'generate.print': 'Печать',
  'generate.docxSoon': 'DOCX пока не готов',
  'generate.exporting': 'Идёт экспорт',
  'generate.saved': 'Работа сгенерирована',
  'generate.questionUpdated': 'Вопрос обновлён',
  'generate.tab.document': 'Документ',
  'generate.tab.key': 'Критерии оценивания',
  'generate.criteria.question': 'Вопрос',
  'generate.criteria.level': 'Критерий',
  'generate.criteria.marks': 'Балл',
  'generate.criteria.full': 'Записан полный ход решения и верный ответ',
  'generate.criteria.partial': 'Ответ верный, но ход решения не записан',
  'generate.criteria.start': 'Выбран верный метод, решение не завершено',
  'generate.criteria.note':
    'Критерии составляются автоматически для каждого вопроса. Учитель может их изменить.',

  'check.title': 'Проверка работ',
  'check.subtitle': 'Загрузите работы учеников — получите баллы и разбор ошибок.',
  'check.dropTitle': 'Перетащите файлы сюда',
  'check.dropBody': 'PDF, JPG или PNG. Один файл — одна работа.',
  'check.browse': 'Выбрать файлы',
  'check.uploadDemo': 'Добавить демо-файлы',
  'check.queue': 'Загруженные файлы',
  'check.process': 'Начать проверку',
  'check.processing': 'Проверяем',
  'check.removeFile': 'Убрать файл {name}',
  'check.status.queued': 'В очереди',
  'check.status.uploading': 'Загрузка',
  'check.status.processing': 'Проверка',
  'check.status.done': 'Готово',
  'check.status.failed': 'Ошибка',
  'check.results': 'Результаты',
  'check.col.student': 'Ученик',
  'check.col.score': 'Балл',
  'check.col.file': 'Файл',
  'check.emptyTitle': 'Загруженных работ нет',
  'check.emptyBody': 'Перетащите файлы в область выше или добавьте демо-файлы.',
  'check.noResultsTitle': 'Результатов нет',
  'check.noResultsBody': 'Загрузите файлы и запустите проверку.',
  'check.detail': 'Детали работы',
  'check.detailFor': '{student} — результат работы',
  'check.breakdown': 'По вопросам',
  'check.question': 'Вопрос {n}',
  'check.override': 'Исправить балл',
  'check.overrideLabel': 'Новый балл',
  'check.overrideSave': 'Сохранить балл',
  'check.overridden': 'Исправлено учителем',
  'check.overrideSaved': 'Балл обновлён',
  'check.exportResults': 'Экспорт результатов',
  'check.fileFailed': 'Не удалось распознать файл. Возможно, снимок нечёткий.',
  'check.processed': 'Проверено работ: {n}',

  'billing.title': 'Баланс',
  'billing.subtitle': 'Полностью прозрачно: за что и сколько списано.',
  'billing.balance': 'Текущий баланс',
  'billing.topUp': 'Пополнить',
  'billing.topUpTitle': 'Пополнение баланса',
  'billing.topUpAmount': 'Сумма',
  'billing.topUpDone': 'Баланс пополнен',
  'billing.zeroTitle': 'Баланс нулевой',
  'billing.zeroBody': 'Чтобы продолжить, пополните баланс.',
  'billing.lowTitle': 'Баланс заканчивается',
  'billing.lowBody': 'При текущем темпе хватит примерно на неделю.',
  'billing.usage': 'Расходы за месяц',
  'billing.period': 'Период',
  'billing.period.month': 'Этот месяц',
  'billing.period.quarter': 'Последние 3 месяца',
  'billing.period.year': 'Этот год',
  'billing.prices': 'Стоимость действий',
  'billing.price.explanation': 'Объяснение с анимацией',
  'billing.price.assessment': 'Одна работа СОР/СОЧ или тест',
  'billing.price.grading': 'Одна проверенная работа',
  'billing.history': 'Транзакции',
  'billing.col.action': 'Действие',
  'billing.col.qty': 'Кол-во',
  'billing.col.amount': 'Сумма',
  'billing.action.explanation': 'Объяснение',
  'billing.action.assessment': 'Работа',
  'billing.action.grading': 'Проверка работы',
  'billing.action.topup': 'Пополнение',
  'billing.historyEmptyTitle': 'Транзакций нет',
  'billing.historyEmptyBody': 'Список появится после первого действия.',
  'billing.exportHistory': 'Экспорт истории',
  'billing.txTitle': 'Транзакция',
  'billing.demoState': 'Демо-состояние баланса',
  'billing.state.healthy': 'Достаточно',
  'billing.state.low': 'Мало',
  'billing.state.zero': 'Ноль',
  'billing.chartLabel': 'Ежедневные расходы за период «{period}», в тенге',
  'billing.spentTotal': 'Всего потрачено',
  'billing.explanations': 'Объяснения',
  'billing.assessments': 'Работы',
  'billing.gradings': 'Проверки',

  'settings.title': 'Настройки',
  'settings.profile': 'Профиль',
  'settings.profileDesc': 'Имя, email и аватар.',
  'settings.avatar': 'Аватар',
  'settings.avatarHint': 'Собирается из первых букв имени и фамилии.',
  'settings.language': 'Язык',
  'settings.languageDesc': 'Язык интерфейса и язык объяснений по умолчанию.',
  'settings.uiLang': 'Язык интерфейса',
  'settings.explainLang': 'Язык объяснений по умолчанию',
  'settings.theme': 'Тема',
  'settings.themeDesc': 'Светлая или тёмная.',
  'settings.theme.light': 'Светлая',
  'settings.theme.dark': 'Тёмная',
  'settings.theme.system': 'Как в системе',
  'settings.plan': 'Тариф',
  'settings.planDesc': 'Текущий тариф и оплата.',
  'settings.plan.student': 'Ученик — бесплатно',
  'settings.plan.teacher': 'Учитель — оплата по факту',
  'settings.plan.studentBody': 'Неограниченные объяснения и библиотека.',
  'settings.plan.teacherBody': 'Все возможности. Каждое действие списывается с баланса.',
  'settings.danger': 'Опасная зона',
  'settings.dangerDesc': 'Удаление аккаунта необратимо.',
  'settings.deleteAccount': 'Удалить аккаунт',
  'settings.deleteTitle': 'Удалить аккаунт?',
  'settings.deleteBody':
    'Все объяснения, библиотека и история будут удалены. Для подтверждения введите {word}.',
  'settings.deleteConfirmLabel': 'Слово подтверждения',
  'settings.deleteWord': 'УДАЛИТЬ',
  'settings.deleteMismatch': 'Слово подтверждения не совпадает',
  'settings.savedToast': 'Изменения сохранены',
  'settings.saveError': 'Не удалось сохранить. Попробуйте ещё раз.',
  'settings.saving': 'Сохраняем',
}

export const en: Record<StringKey, string> = {
  'app.name': 'Anyq',
  'app.tagline': 'Turn your question into an animation',

  'common.signIn': 'Sign in',
  'common.signUp': 'Sign up',
  'common.logOut': 'Sign out',
  'common.save': 'Save',
  'common.saved': 'Saved',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.retry': 'Try again',
  'common.search': 'Search',
  'common.open': 'Open',
  'common.rename': 'Rename',
  'common.export': 'Export',
  'common.loading': 'Loading',
  'common.language': 'Language',
  'common.kazakh': 'Kazakh',
  'common.russian': 'Russian',
  'common.auto': 'Auto',
  'common.subject': 'Subject',
  'common.grade': 'Grade',
  'common.topic': 'Topic',
  'common.date': 'Date',
  'common.status': 'Status',
  'common.actions': 'Actions',
  'common.all': 'All',
  'common.confirm': 'Confirm',
  'common.required': 'required',
  'common.menu': 'Menu',
  'theme.toLight': 'Switch to the light theme',
  'theme.toDark': 'Switch to the dark theme',
  'theme.label': 'Appearance',
  'common.of': '/',

  'subject.math': 'Maths',
  'subject.geometry': 'Geometry',
  'subject.physics': 'Physics',
  'subject.chemistry': 'Chemistry',
  'subject.biology': 'Biology',
  'subject.informatics': 'Computer science',

  'role.student': 'Student',
  'role.teacher': 'Teacher',
  'role.studentDesc':
    'Ask questions, get an explanation and an animation, save them to your library.',
  'role.teacherDesc':
    'All of that, plus assessment generation, marking and a usage balance.',

  'nav.explain': 'Explain',
  'nav.library': 'Library',
  'nav.generate': 'Generate',
  'nav.check': 'Check',
  'nav.billing': 'Billing',
  'nav.settings': 'Settings',

  'landing.nav.how': 'How it works',
  'landing.nav.examples': 'Examples',
  'landing.nav.about': 'About us',
  'landing.hero.title': 'Any question, as a short animated explanation',
  'landing.hero.subtitle':
    'Write your question in Kazakh or Russian. Anyq works through it step by step and turns the explanation into a geometric animation. In minutes, not days.',
  'landing.hero.cta': 'Start free',
  'landing.hero.secondary': 'See examples',
  'landing.hero.caption':
    'The Pythagorean theorem — a frame from an animation made by Anyq.',
  'landing.compare.title': 'Easier to see than to read',
  'landing.compare.subtitle':
    'Drag the handle left or right. On the left is the textbook text; on the right is the animation made from it.',
  'landing.compare.hint': 'Drag the handle',
  'landing.compare.textLabel': 'Textbook text',
  'landing.compare.videoLabel': 'Anyq animation',
  'landing.compare.sliderLabel': 'Handle comparing the text with the animation',
  'landing.compare.textTitle': 'The Pythagorean theorem',
  'landing.compare.textBody':
    'The square of the hypotenuse of a right triangle equals the sum of the squares of its legs. To prove it, build a square with side a + b and place four identical right triangles with legs a and b inside it. Arranging the triangles in two different ways leaves a free area of a² + b² in the first case and c² in the second. Since the total area of the removed triangles is the same in both cases, the remaining areas are equal too: a² + b² = c². It follows that the hypotenuse has length c = √(a² + b²). The theorem holds for every right triangle, and its converse is true as well: if the sides of a triangle satisfy a² + b² = c², then the triangle is right-angled.',
  'landing.how.title': 'Three steps',
  'landing.how.step1.title': 'Ask',
  'landing.how.step1.body':
    'Write the question in your own words. The language is detected automatically, and you can override it.',
  'landing.how.step2.title': 'Explain',
  'landing.how.step2.body':
    'Anyq breaks the answer into steps: what is given, which rule applies, what the result is.',
  'landing.how.step3.title': 'Animate',
  'landing.how.step3.body':
    'Each step becomes a geometric scene. The result is a short explainer video, ready in minutes.',
  'landing.examples.title': 'Ready-made examples',
  'landing.examples.subtitle': 'All made with Anyq. Hover to play.',
  'landing.examples.play': 'Hover to play',
  'landing.why.title': 'Why Kazakh?',
  'landing.why.body1':
    'A single animated explanation takes an animator several days by hand. For a language with a small audience, producing that content at scale is not economically viable. As a result, quality visual learning material in Kazakh barely exists.',
  'landing.why.body2':
    'Anyq automates that work. While students in larger languages watch visual explanations, a Kazakh-speaking student should not be left alone with a wall of text.',
  'landing.why.stat1': 'One animation by hand',
  'landing.why.stat1v': '3–5 days',
  'landing.why.stat2': 'With Anyq',
  'landing.why.stat2v': '4 minutes',
  'landing.why.stat3': 'Kazakh',
  'landing.why.stat3v': 'Default language',
  'landing.team.title': 'Who built it',
  'landing.team.subtitle': 'A team of two.',
  'landing.contact.title': 'Have a question?',
  'landing.contact.body': 'Get in touch about anything — we are glad to answer.',
  'landing.contact.phone': 'Phone',
  'landing.contact.email': 'Email',
  'landing.cta.title': 'Ask your first question',
  'landing.cta.body': 'Signing up is free. Unlimited explanations for students.',
  'landing.footer.product': 'Product',
  'landing.footer.company': 'Company',
  'landing.footer.legal': 'Legal',
  'landing.footer.privacy': 'Privacy policy',
  'landing.footer.terms': 'Terms of use',
  'landing.footer.contact': 'Contact',
  'landing.footer.rights': 'All rights reserved.',

  'auth.signup.title': 'Sign up',
  'auth.signup.subtitle': 'Takes a minute. No card needed.',
  'auth.signup.roleLabel': 'Who are you?',
  'auth.signup.roleError': 'Choose a role',
  'auth.signup.submit': 'Create account',
  'auth.signup.haveAccount': 'Already have an account?',
  'auth.signin.title': 'Welcome back',
  'auth.signin.subtitle': 'Return to your workspace.',
  'auth.signin.submit': 'Sign in',
  'auth.signin.noAccount': 'No account yet?',
  'auth.signin.forgot': 'Forgot your password?',
  'auth.signin.invalid': 'Wrong email or password. Please try again.',
  'auth.field.name': 'Full name',
  'auth.field.email': 'Email',
  'auth.field.password': 'Password',
  'auth.error.nameRequired': 'Enter your name',
  'auth.error.emailRequired': 'Enter an email',
  'auth.error.emailInvalid': 'That email format is not valid',
  'auth.error.passwordRequired': 'Enter a password',
  'auth.error.passwordShort': 'At least 8 characters',
  'auth.error.form': 'Please complete the form.',
  'auth.error.emailTaken': 'That email is already registered. Try signing in.',
  'auth.error.tooMany': 'Too many attempts. Wait a little.',
  'auth.error.network': 'The server did not answer. Check your connection.',
  'auth.error.unknown': 'Something went wrong. Try again.',
  'auth.password.hint': 'At least 8 characters.',

  'explain.title': 'Explain',
  'explain.history': 'History',
  'explain.newChat': 'New question',
  'explain.historyEmpty': 'No questions yet.',
  'explain.inputLabel': 'Your question',
  'explain.placeholder': 'For example: Why does the sky look blue?',
  'explain.submit': 'Explain',
  'explain.langLabel': 'Answer language',
  'explain.emptyTitle': 'Start with a question',
  'explain.emptyBody':
    'Write any maths or science question. You can also try one of the examples below.',
  'explain.examplesTitle': 'Example questions',
  'explain.stage.understand': 'Reading the question',
  'explain.stage.write': 'Writing the explanation',
  'explain.stage.render': 'Rendering the animation',
  'explain.generatingTitle': 'Working on it',
  'explain.generatingBody':
    'Rendering the animation can take a few minutes. Keep this page open.',
  'explain.resultTitle': 'Explanation',
  'explain.saveToLibrary': 'Save to library',
  'explain.savedToLibrary': 'Saved in your library',
  'explain.partialTitle': 'The animation did not come out',
  'explain.partialBody':
    'The explanation is ready, but the animation could not be produced this time. You can read the text, or ask for the animation again.',
  'explain.partialRetry': 'Build the animation again',
  'explain.errorTitle': 'Something went wrong',
  'explain.errorBody':
    'We could not prepare an answer to this question. Reword it or send it again.',
  'explain.demoLabel': 'Demo state',
  'explain.demo.ok': 'Success',
  'explain.demo.partial': 'No animation',
  'explain.demo.error': 'Error',
  'explain.demoHint': 'Demo: choose what the next question returns.',
  'explain.savedToast': 'Saved to your library',
  'explain.costNote': 'One explanation — {cost}',

  'player.play': 'Play',
  'player.pause': 'Pause',
  'player.replay': 'Replay',
  'player.seek': 'Seek',
  'player.label': 'Animation player',
  'player.failed': 'The video could not be played.',
  'player.download': 'Download the video',
  'explain.fromLibrary': 'From the library',
  'explain.fromLibraryHint': 'This question had already been answered, so it arrived at once.',
  'explain.matchedQuestion': 'Answering a similar question: “{question}”',
  'explain.askAgain': 'Ask from scratch',
  'explain.offline': 'No connection to the server. Reconnecting…',
  'explain.timedOut': 'The answer is taking unusually long. If it finished, it is in your history.',
  'explain.noAnswerYet':
    'This question never got an answer. It is back in the box - press Retry.',
  'explain.historyUnreadable': 'That entry could not be opened. Please try again.',
  'explain.failed': 'The explanation could not be produced.',
  'narration.label': 'Voice',
  'narration.on': 'With a voice — about a minute',
  'narration.off': 'Silent — shorter, captions only',
  'narration.enable': 'Turn the voice on',
  'narration.disable': 'Turn the voice off',
  'narration.voice.aigul': 'Aigul',
  'narration.voice.daulet': 'Daulet',
  'narration.voiceLabel': 'Choose a voice',
  'effort.label': 'Quality',
  'effort.low': 'Light',
  'effort.low.hint': '480p, 15 fps',
  'effort.low.wait': 'Fastest',
  'effort.medium': 'Normal',
  'effort.medium.hint': '720p, 30 fps',
  'effort.medium.wait': 'Usual wait',
  'effort.high': 'High',
  'effort.high.hint': '1080p, 60 fps',
  'effort.high.wait': 'Up to a few minutes',
  'length.label': 'Length',
  'length.short': 'Short',
  'length.short.hint': '~30-40 sec',
  'length.medium': 'Medium',
  'length.medium.hint': '~50-60 sec',
  'length.long': 'Long',
  'length.long.hint': '~80-90 sec',
  'player.reducedMotion':
    'Reduced motion is on in your system, so the animation does not play automatically.',

  'library.title': 'Library',
  'library.loadFailed': 'The library could not be loaded.',
  'library.saveFailed': 'The change could not be saved.',
  'library.subtitle': 'Saved explanations.',
  'library.searchPlaceholder': 'Search by question',
  'library.sort.new': 'Newest first',
  'library.sort.old': 'Oldest first',
  'library.sort.az': 'Alphabetical',
  'library.sortLabel': 'Sort',
  'library.count': '{n} explanations',
  'library.emptyTitle': 'Your library is empty',
  'library.emptyBody': 'Explanations you save will collect here.',
  'library.emptyCta': 'Ask your first question',
  'library.noResultsTitle': 'Nothing found',
  'library.noResultsBody': 'Try a different search or filter.',
  'library.clearFilters': 'Clear filters',
  'library.deleteTitle': 'Delete explanation',
  'library.deleteBody':
    '“{title}” will be removed from your library. This cannot be undone.',
  'library.deleted': 'Explanation deleted',
  'library.renameTitle': 'Rename',
  'library.renameLabel': 'New title',
  'library.renamed': 'Title updated',
  'library.cardMenu': '{title} — actions',

  'generate.title': 'Generate an assessment',
  'generate.subtitle': 'СОР, СОЖ or a short quiz.',
  'generate.form': 'Settings',
  'generate.type': 'Assessment type',
  'generate.type.sor': 'СОР',
  'generate.type.soch': 'СОЖ',
  'generate.type.quiz': 'Quiz',
  'generate.topicPlaceholder': 'For example: Quadratic equations',
  'generate.count': 'Number of questions',
  'generate.difficulty': 'Difficulty',
  'generate.difficulty.easy': 'Easy',
  'generate.difficulty.medium': 'Medium',
  'generate.difficulty.hard': 'Hard',
  'generate.submit': 'Generate',
  'generate.regenerate': 'Generate again',
  'generate.preview': 'Preview',
  'generate.previewEmptyTitle': 'No document yet',
  'generate.previewEmptyBody': 'Fill in the settings on the left and press “Generate”.',
  'generate.generating': 'Writing questions',
  'generate.errorTitle': 'Generation failed',
  'generate.errorBody': 'Try again or change the settings.',
  'generate.topicRequired': 'Enter a topic',
  'generate.regenerateQuestion': 'Regenerate question {n}',
  'generate.editQuestion': 'Question {n} text',
  'generate.marks': '{n} marks',
  'generate.totalMarks': 'Total: {n} marks',
  'generate.instructions': 'Instructions',
  'generate.instructionsBody':
    'Answer every question. Write out your full working. Time allowed: 40 minutes.',
  'generate.docHeaderName': 'Full name',
  'generate.docHeaderClass': 'Class',
  'generate.docHeaderDate': 'Date',
  'generate.exportDocx': 'DOCX',
  'generate.print': 'Print',
  'generate.docxSoon': 'DOCX is not ready yet',
  'generate.exporting': 'Exporting',
  'generate.saved': 'Assessment generated',
  'generate.questionUpdated': 'Question updated',
  'generate.tab.document': 'Document',
  'generate.tab.key': 'Marking scheme',
  'generate.criteria.question': 'Question',
  'generate.criteria.level': 'Criterion',
  'generate.criteria.marks': 'Marks',
  'generate.criteria.full': 'Full working shown and the answer is correct',
  'generate.criteria.partial': 'Answer is correct but no working is shown',
  'generate.criteria.start': 'Correct method chosen, solution not finished',
  'generate.criteria.note':
    'Criteria are drafted automatically for each question. Teachers can edit them.',

  'check.title': 'Check student work',
  'check.subtitle': 'Upload student work and get marks with a breakdown of the mistakes.',
  'check.dropTitle': 'Drop files here',
  'check.dropBody': 'PDF, JPG or PNG. One file per student.',
  'check.browse': 'Choose files',
  'check.uploadDemo': 'Add demo files',
  'check.queue': 'Uploaded files',
  'check.process': 'Start checking',
  'check.processing': 'Checking',
  'check.removeFile': 'Remove file {name}',
  'check.status.queued': 'Queued',
  'check.status.uploading': 'Uploading',
  'check.status.processing': 'Checking',
  'check.status.done': 'Done',
  'check.status.failed': 'Failed',
  'check.results': 'Results',
  'check.col.student': 'Student',
  'check.col.score': 'Score',
  'check.col.file': 'File',
  'check.emptyTitle': 'Nothing uploaded yet',
  'check.emptyBody': 'Drop files into the area above, or add the demo files.',
  'check.noResultsTitle': 'No results',
  'check.noResultsBody': 'Upload files and start the check.',
  'check.detail': 'Submission detail',
  'check.detailFor': '{student} — result',
  'check.breakdown': 'By question',
  'check.question': 'Question {n}',
  'check.override': 'Override the mark',
  'check.overrideLabel': 'New mark',
  'check.overrideSave': 'Save mark',
  'check.overridden': 'Changed by the teacher',
  'check.overrideSaved': 'Mark updated',
  'check.exportResults': 'Export results',
  'check.fileFailed': 'We could not read this file. The photo may be out of focus.',
  'check.processed': '{n} submissions checked',

  'billing.title': 'Billing',
  'billing.subtitle': 'Fully transparent: what was charged, and for what.',
  'billing.balance': 'Current balance',
  'billing.topUp': 'Top up',
  'billing.topUpTitle': 'Top up your balance',
  'billing.topUpAmount': 'Amount',
  'billing.topUpDone': 'Balance topped up',
  'billing.zeroTitle': 'Your balance is empty',
  'billing.zeroBody': 'Top up your balance to keep going.',
  'billing.lowTitle': 'Balance running low',
  'billing.lowBody': 'At the current rate this lasts about a week.',
  'billing.usage': 'Spending this month',
  'billing.period': 'Period',
  'billing.period.month': 'This month',
  'billing.period.quarter': 'Last 3 months',
  'billing.period.year': 'This year',
  'billing.prices': 'Cost per action',
  'billing.price.explanation': 'One explanation with animation',
  'billing.price.assessment': 'One СОР/СОЖ or quiz',
  'billing.price.grading': 'One marked submission',
  'billing.history': 'Transactions',
  'billing.col.action': 'Action',
  'billing.col.qty': 'Qty',
  'billing.col.amount': 'Amount',
  'billing.action.explanation': 'Explanation',
  'billing.action.assessment': 'Assessment',
  'billing.action.grading': 'Marking',
  'billing.action.topup': 'Top-up',
  'billing.historyEmptyTitle': 'No transactions',
  'billing.historyEmptyBody': 'The list appears after your first action.',
  'billing.exportHistory': 'Export history',
  'billing.txTitle': 'Transaction',
  'billing.demoState': 'Demo balance state',
  'billing.state.healthy': 'Healthy',
  'billing.state.low': 'Low',
  'billing.state.zero': 'Empty',
  'billing.chartLabel': 'Daily spending for {period}, in tenge',
  'billing.spentTotal': 'Total spent',
  'billing.explanations': 'Explanations',
  'billing.assessments': 'Assessments',
  'billing.gradings': 'Marked',

  'settings.title': 'Settings',
  'settings.profile': 'Profile',
  'settings.profileDesc': 'Name, email and avatar.',
  'settings.avatar': 'Avatar',
  'settings.avatarHint': 'Built from the initials of your name.',
  'settings.language': 'Language',
  'settings.languageDesc': 'Interface language and the default explanation language.',
  'settings.uiLang': 'Interface language',
  'settings.explainLang': 'Default explanation language',
  'settings.theme': 'Appearance',
  'settings.themeDesc': 'Light or dark.',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.theme.system': 'Match system',
  'settings.plan': 'Plan',
  'settings.planDesc': 'Your current plan and billing.',
  'settings.plan.student': 'Student — free',
  'settings.plan.teacher': 'Teacher — pay as you go',
  'settings.plan.studentBody': 'Unlimited explanations and library.',
  'settings.plan.teacherBody':
    'Everything included. Each action is charged to your balance.',
  'settings.danger': 'Danger zone',
  'settings.dangerDesc': 'Deleting your account cannot be undone.',
  'settings.deleteAccount': 'Delete account',
  'settings.deleteTitle': 'Delete your account?',
  'settings.deleteBody':
    'Every explanation, your library and your history will be deleted. Type {word} below to confirm.',
  'settings.deleteConfirmLabel': 'Confirmation word',
  'settings.deleteWord': 'DELETE',
  'settings.deleteMismatch': 'The confirmation word does not match',
  'settings.savedToast': 'Changes saved',
  'settings.saveError': 'Could not save. Please try again.',
  'settings.saving': 'Saving',
}
